### ISSUE TITLE
## Espaçamentos e caracteres especiais de listagem

### ISSUE THREAD

**Issue by Ckk3** [filiperochalopes/filipelopes.me#36]
## Espaçamentos e caracteres especiais de listagem
![image](https://user-images.githubusercontent.com/34348097/219985933-16ca789a-3a42-4a85-845a-c1b02f281d1b.png). 
Azul: O texto de todas as páginas devem respeitar as margens e limite da linha.  
Laranja: Observar que a coluna da esquerda fica com o texto muito colado na barra, acho que dá para chegar a barra um pouco mais para a direita, respeitando a equidistancia do conteudo da direita e esquerda. 
Vermelho: Repare que na referência temos um respiro aqui. 
Roxo: Para facilitar a legibilidade esses traços devem ser substituídos por pontos como na referência (isso pode ser feito com regex replace) e adicionar um espaçamento à direita do ponto de item, pode ser feito com o mesmo método.

_Originally posted by @filiperochalopes in https://github.com/filiperochalopes/filipelopes.me/issues/34#issuecomment-1436154162_

**Comment by Ckk3** [comment]
Existe alguns impedimentos ao resolver esse problema. 
- A fonte não possui os mesmos espaçamentos para todos os caracteres, ou seja, perco a principal métrica que eu utilizava, os caracteres. Irei utilizar um método próprio de calcular a posição do caractere na página e "quebrar a linha" utilizando essa posição. 
- Infelizmente, separar por cada caracteres fica difícil já que a biblioteca não utiliza sequer a quebra de linha (utilizo um método que eu mesmo criei), e a inserção é feita por um texto completo e não por cada caractere. 
- Enfim, para resumir, precisarei criar um novo modelo de inserção de texto para ai sim alterar essa quebra de linha, ou podemos trocar a fonte para alguma com o mesmo tamanho para cada caractere.

**Comment by filiperochalopes** [comment]
1. Não é possível criar um container de largura fixa para que os textos passam completá-los e quebrar ao fim do tamanho do mesmo? Se não podemos utilizar o tamanho dos caracteres nesse exemplo temos que buscar novas formas de alinhar as estruturas.
2. Não entendi o que quis dizer por separar cada caractere. De qual parte do documento estamos falando, em azul, laranja, vermelho ou roxo?
3. Creio que a primeira opção é a única viável para esse documento.

**Comment by Ckk3** [comment]
> 1. Não é possível criar um container de largura fixa para que os textos passam completá-los e quebrar ao fim do tamanho do mesmo? Se não podemos utilizar o tamanho dos caracteres nesse exemplo temos que buscar novas formas de alinhar as estruturas.
> 2. Não entendi o que quis dizer por separar cada caractere. De qual parte do documento estamos falando, em azul, laranja, vermelho ou roxo?
> 3. Creio que a primeira opção é a única viável para esse documento.

os detalhes de impedimento foram somente em relação à quebra de linha, delimitado em azul, já estou trabalhando em uma correção

**Comment by Ckk3** [comment]
Resolvido!
